{
  "errors": [
    {
      "code": "INTERNAL_SERVER_ERROR",
      "message": "An unexpected error occurred",
      "details": "Please try again later or contact support"
    }
  ],
  "timestamp": "2024-01-01T12:00:00Z",
  "traceId": "7889ed42-8a28-4526-9c15-503ba42fb6c1",
  "status": 500,
  "path": "Update product by ID"
}