{
  "errors": [
    {
      "code": "INTERNAL_SERVER_ERROR",
      "message": "An unexpected error occurred",
      "details": "Please try again later or contact support"
    }
  ],
  "timestamp": "2024-01-01T12:00:00Z",
  "traceId": "b129afc5-4514-41fa-b31f-4e99098c8ebf",
  "status": 500,
  "path": "Update product by ID"
}