{
  "errors": [
    {
      "code": "INTERNAL_SERVER_ERROR",
      "message": "An unexpected error occurred",
      "details": "Please try again later or contact support"
    }
  ],
  "timestamp": "2024-01-01T12:00:00Z",
  "traceId": "b9747a56-bd69-4d3b-afb5-00dedc2e4640",
  "status": 500,
  "path": "Update product by ID"
}